### ISSUE TITLE
E2E Encryption: Double Ratched

### ISSUE THREAD

**Issue by 0xdevalias** [levelhq/level#47]
It would be great to implement some e2e encryption. Current 'best standard' by my knowledge is the 'Double Ratchet' algorithm implemented by Signal:

* https://en.wikipedia.org/wiki/Double_Ratchet_Algorithm
* https://github.com/matrix-org/olm

**Comment by derrickreimer** [comment]
Thanks for filing this. I need to educate myself on what an implementation of this would look like. A few questions I'm thinking about:

- Do all recipients of messages need to be determined in advance of the message being encrypted? Since Level is designed to be shared repository of information for an organization, it's important to be able to loop-in people after the fact.
- Would messages be search-indexable, or would that defeat the purpose of E2E encryption?

**Comment by derrickreimer** [comment]
Moving this one to my own backlog of feature requests.
