### ISSUE TITLE
Minimize the Tailwind bundle size

### ISSUE THREAD

**Issue by derrickreimer** [levelhq/level#84]
Follow these instructions: https://tailwindcss.com/docs/controlling-file-size

**Comment by sleepiejohn** [comment]
What about instead we pick by hand the properties we want using the configuration file, we use [PurgeCSS](https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css-with-purgecss) with webpack, so the output css is just what we are using ?

**Comment by derrickreimer** [comment]
Not a bad idea. Two open questions/concerns:

1. It is mature/reliable enough not to break stuff? Looks like it just crossed 1.0. Will want to do a little investigation first to vet it enough.
2. Does it work with styles in Elm files? This would be a deal-breaker if not.

**Comment by sleepiejohn** [comment]
I did some exploration over the code base, here my findings:
- Is it mature enough? I would say so, it was supposed to be v2 of [purifycss](https://github.com/purifycss/purifycss) but evolved to be something else inspired by it.
- Does it work with Elm? I was hoping that it would because it works with other templates, but there were functions on elm that returned the necessary class to apply so those didn't get recognized.

Just for reference the sizes were without minification:

|  PurgeCSS | w/o Purge  | 
|---|---|
|  24kb  |  194kb  |  

I will try to come up with some configuration on `tailwind.js`  seems more reliable.

**Comment by sleepiejohn** [comment]
Without purging, but enabling minification it goes from `194kb` to `133kb`

**Comment by derrickreimer** [comment]
Closing this for now. Current size of the css file is 31.9 kb gzipped, so not too concerned at this stage.
